language: python
env:
  matrix:
  - TOX_ENV=python
  - TOX_ENV=flake8
  - TOX_ENV=spelling
  - TOX_ENV=package
install:
- sudo apt-get install python-enchant -y
- pip install --upgrade pip
- pip install tox coveralls
script:
- tox -e $TOX_ENV
after_success: coveralls
deploy:
- provider: pypi
  user: Myoldmopar
  skip_cleanup: true
  password:
    secure: pvFbYMHUxv37b4Y5kiLpKS6BiEqsMQfi+mduJzRExmzPRh9kRxg2oUkgMS/R6Ho5Aig+fz3oJCILmTTzqXrn5tARMkbz1scIKOYOpVHVumBGH1PorWTAggcQAs/YC0MdoljIa7ONfcLLHG2b4aPqVKWxU21O5cAYjiO7ejuLZPl3MhduH+n/QVoyti2mMow/cJEn3zyIuOKtP6i5BjegrRX6fxiwb+7XNpozrkmH8nVH8Xxvf3uMNUfTapwTgdwUeBVTBu65U2AgRgmhe5tSTYGrUU2lOBw2ZZcYQxVWwPGfOcgTO+tL07SLOCbagyRAQQM2d/ujCPShxt4iEjZZwi7mXLhG4vjgvHOzPqlB4howZK73wlDmR+hVFXWYmVVm583XF333XJ/MEDVoI78s2JzSTP0OHOnS/LIqzSB8R/VCK6+m17VOeKdEJEEgc8Wf6tJ5AmhN1iHjfgfmTcQo+ynl7VsU+LRAxqWQSdeV66j83imYY05SMdhCUJJ3WLwaTmKO+uYGcRZNbxMi/DGVxbBxOk3e+CyiNKdJgLcF/z8IThcCdEVOImZxBlj+/967DELnMYfi0ipiCAO/erO33XegRXX9bzJ6Bj4Ld10LPecJpTUmrzope6HVH7Xiv5s18sYeh597RSsAsaCKhfUO+QaFVobmla8hTVRswJ5brkA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Myoldmopar/ep-transition
    condition: $TOX_ENV = package
- provider: releases
  skip_cleanup: true
  api_key:
    secure: k+mg38vs1FT7SgCf//Yl35G6S5oGl/Ujz/iTBrKx9pkUvqKb+pL8xq3p+xNBCVyCQZvvFfnMI0Se6ZyJt0PsjkZOJtSIfUgtvL8G6LqINyef7VFOyu92d15e2mEyshwtl6eumzHC74+XZJuQJLp9rvZfogy3oBypPO9rCcIzMZ2KaZ+2+SEEMKAnSjrpLBm6CRN8BneV8D+Wma8CpzgPHRS3G0Aa8rxtAUTi8A9GWUFMi+rWF8odAB4krDsylvTh5hBqlbtDN2Io2CzcEk8gGdEI5Q9kRaMfh+QtZJlU4FuIKtnDvM59MWxnsAzdxeCsoV076qqspSp6aHb7Y7XiOCL1LGuvWPP8k5ALEyZUob+IU/74dQItxoc40ftZvWSpuX//KdgHp1W0ZxDSwUj2+Pl7aIQn5eexlJaCAEE4LVEbWYa9GBRAuDmbiVAm/xPu+F1VIOlrI5OtINua5ATZMNOmpqiHlE7neqBcHjJDndRJ5u+hdMRD3ud1KGj0RqnZwYogl0vasq65oya8TsIgnJrySHVOC3jMpg6z8xIZpacpJmk1lsjs4d+ygEdEicazXe/VkTw9rfY+7LaR81ynjG1OaTerCxZGmIOU0l8CnzBbklfiAvpfJw7GXvkyyTngnmmxM96D1QQr4HHYWqw6kO18XEhwxYI5BvBCE7s/exs=
  file: dist/ep-transition-wheel.zip
  on:
    tags: true
    condition: $TOX_ENV = package