language: python
env:
  matrix:
  - TOX_ENV=python
  - TOX_ENV=flake8
  - TOX_ENV=spelling
  - TOX_ENV=package
install:
- sudo apt-get install python-enchant -y
- pip install --upgrade pip
- pip install tox coveralls
script:
- tox -e $TOX_ENV
after_success: coveralls
deploy:
  provider: pypi
  user: Myoldmopar
  password:
    secure: pvFbYMHUxv37b4Y5kiLpKS6BiEqsMQfi+mduJzRExmzPRh9kRxg2oUkgMS/R6Ho5Aig+fz3oJCILmTTzqXrn5tARMkbz1scIKOYOpVHVumBGH1PorWTAggcQAs/YC0MdoljIa7ONfcLLHG2b4aPqVKWxU21O5cAYjiO7ejuLZPl3MhduH+n/QVoyti2mMow/cJEn3zyIuOKtP6i5BjegrRX6fxiwb+7XNpozrkmH8nVH8Xxvf3uMNUfTapwTgdwUeBVTBu65U2AgRgmhe5tSTYGrUU2lOBw2ZZcYQxVWwPGfOcgTO+tL07SLOCbagyRAQQM2d/ujCPShxt4iEjZZwi7mXLhG4vjgvHOzPqlB4howZK73wlDmR+hVFXWYmVVm583XF333XJ/MEDVoI78s2JzSTP0OHOnS/LIqzSB8R/VCK6+m17VOeKdEJEEgc8Wf6tJ5AmhN1iHjfgfmTcQo+ynl7VsU+LRAxqWQSdeV66j83imYY05SMdhCUJJ3WLwaTmKO+uYGcRZNbxMi/DGVxbBxOk3e+CyiNKdJgLcF/z8IThcCdEVOImZxBlj+/967DELnMYfi0ipiCAO/erO33XegRXX9bzJ6Bj4Ld10LPecJpTUmrzope6HVH7Xiv5s18sYeh597RSsAsaCKhfUO+QaFVobmla8hTVRswJ5brkA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Myoldmopar/ep-transition
