language: python

os:
  - linux
  - osx

env:
  matrix:
    - TOX_ENV=python
    - TOX_ENV=flake8
    - TOX_ENV=spelling
    - TOX_ENV=py2app

install:
  - sudo apt-get install python-enchant -y
  - pip install --upgrade pip
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success: coveralls

deploy:
  provider: releases
  skip_cleanup: true
  file: dist/ep-transition-wheel.zip
  on:
    tags: true
  api-key:
    secure: Y5BJpXmGlPGvGovo8NFVjHfZYBlkF0LITNgwj1CVAjI0PWTwaKJXEtZ3bDvoRaBvt3K9u/gFVFIxUIEs1azYSUBQpf94Ac1s6q+XUKWpINx66v2iSP4a9N1pacCwBI2l2ho9zskaEEqZF4pP+ScAwWpOYh06tOSKePifQW+Qlvavdd+SZCBlpxl2WQufhBHfigfCKaHc3hFUyUu5pLvoIcPDVjfDQP3tNi3N72zGTCWE4h513QHyXOkJxs2QkCNn7MmXig/oLRtYYB4ryuZxwDjoUU4Fi5AJK6lTsAox0cifnEmuKGwPOIsfW4pfoHTix3a4MyejBDk2p12SYhT0TCytN0+vzyLK2yFfeOj32Ww3VzLk7/s3CL7YQuSafRhw08ktitPdoYCJEXAZuUSrEUVkIPsYOWgh6k5ie7XXs9lSm3EMm5j/MwzjJQ/egGNH69sgy1MsyOBnBRd0i/2jNDg615X9j4ndxlmmOkWzq+OH8EhOXcZw+qbfe1U1UEUAr28iPhthxGjvpCwJlRPPgPcGrJAyDS+2lVnw4bFvc4tu/nmOGj2QL79t1C5KB8D10yvEAkMudIfebVArqJ5v3svovVAf8fKsBoitFjeqMRxTZRlh94ySdkP8vKd5orWwpfbkcDkV6LISHC1RXonSPTUBcggdQ0Se+zKHBIGmUzU=